### ISSUE TITLE
`:TabmodeEnter` in Neovim produces `E129: Function name required`

### ISSUE THREAD

**Issue by galou** [Iron-E/vim-tabmode#1]
I like `vim-tabmode` a lot but I run into a small issue. `:TabmodeEnter` in Neovim produces `E129: Function name required`. I use Neovim v0.5.0-dev and `vim-libmodal` (`nvim-libmodal` is incompatible with `vim-tabmode`).

It's a small issue because the default binding (in normal mode `\<Tab>` bound to`<Plug>TabmodeEnter`) works.

**Comment by Iron-E** [comment]
Thanks for the bug report!

I can reproduce this on Neovim 0.4.3 and Neovim 0.5, so I believe it isn't specific to the nightly edition. I'll take a look and report back.

Out of curiosity, though, is there any reason you aren't using [nvim-tabmode](https://github.com/Iron-E/nvim-tabmode)? If there's a discrepancy in functionality I'd like to address that too.

Either way this should be working in both Neovim and Vim, so I'll get this fixed.

**Comment by Iron-E** [comment]
Can you verify that the `bugfix/1.0.5` branch is working for you? Instructions for `dein.vim` are [here](https://github.com/Shougo/dein.vim#options) if you haven't done it before.

It's working for me now, and if it's working for you I can merge it.

I have also added a `bugfix/1.0.2` branch on `nvim-libmodal` if you wish to try that instead— it turns out both repositories had the same issue (as `nvim-libmodal` was based off of `vim-libmodal`).

**Comment by galou** [comment]
The reason why I didn't use `nvim-tabmode` is simple, I didn't know about it.
Both `vim-tabmode:bugfix/1.0.5` and ``nvim-tabmode:bugfix/1.0.2` work.

Thanks!
